package com.syang.yame.registry;

import com.syang.yame.Yame;
import com.syang.yame.world.item.ModAlloy;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.item.equipment.ArmorMaterial;
import net.minecraft.world.item.equipment.ArmorType;
import net.minecraft.world.item.equipment.EquipmentAsset;
import net.minecraft.world.item.equipment.EquipmentAssets;

import java.util.EnumMap;
import java.util.Map;

/**
 * One {@link ArmorMaterial} per alloy. Since 1.21.2 an armor material is a plain record (there is
 * no registry any more): the item gets its stats via {@code Item.Properties#humanoidArmor}, and the
 * worn model comes from the {@link EquipmentAsset} the material points at —
 * {@code assets/yame/equipment/<alloy>.json} (data-generated by {@code ModEquipmentAssetProvider}),
 * whose humanoid layers reference
 * {@code assets/yame/textures/entity/equipment/humanoid/<alloy>.png} (and {@code humanoid_leggings/}).
 *
 * <p>The repair ingredient is the alloy's own ingot, via the per-alloy item tag
 * {@link ModAlloy#repairTag()} (tags are how 1.21.2+ expresses repair materials).
 */
public final class ModArmorMaterials {

    public static final Map<ModAlloy, ResourceKey<EquipmentAsset>> ASSETS = new EnumMap<>(ModAlloy.class);
    public static final Map<ModAlloy, ArmorMaterial> BY_ALLOY = new EnumMap<>(ModAlloy.class);

    static {
        for (ModAlloy alloy : ModAlloy.values()) {
            ASSETS.put(alloy, ResourceKey.create(EquipmentAssets.ROOT_ID,
                    Identifier.fromNamespaceAndPath(Yame.MOD_ID, alloy.id())));
            BY_ALLOY.put(alloy, createMaterial(alloy));
        }
    }

    private ModArmorMaterials() {
    }

    private static ArmorMaterial createMaterial(ModAlloy alloy) {
        ModAlloy.ArmorPreset preset = alloy.armorPreset();

        Map<ArmorType, Integer> defense = new EnumMap<>(ArmorType.class);
        defense.put(ArmorType.HELMET, preset.helmet());
        defense.put(ArmorType.CHESTPLATE, preset.chest());
        defense.put(ArmorType.LEGGINGS, preset.leggings());
        defense.put(ArmorType.BOOTS, preset.boots());
        defense.put(ArmorType.BODY, preset.chest());

        return new ArmorMaterial(
                preset.durabilityMult(),
                defense,
                alloy.enchantmentValue(),
                SoundEvents.ARMOR_EQUIP_IRON,
                preset.toughness(),
                preset.knockbackResistance(),
                alloy.repairTag(),
                ASSETS.get(alloy)
        );
    }
}
